# .rubocop.yml
AllCops:
  NewCops: enable 
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "views/*"
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Max: 30
Metrics/MethodLength:
  Max: 20